# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Acerca del evento
    url: '#acerca'
    weight: 10
  - name: Equipo organizador
    url: '#equipo'
    weight: 20
  - name: Programa
    url: 'programa'
    weight: 30
  - name: Patrocinadores y Colaboradores
    url: 'patrocinadores_y_colaboradores'
    weight: 40
  - name: Programa de Mentoreo
    url: 'mentoreo'
    weight: 50
  - name: Divulgaci√≥n
    url: 'divulgacion'
    weight: 60
  - name: Contacto
    url: '#contacto'
    weight: 70
